### ISSUE TITLE
Provided d.ts miss most of RequestBuilder's functions.

### ISSUE THREAD

**Issue by pawelpawlow** [aurelia/http-client#71] opened 2015-07-17 08:20 UTC
RequestBuilder typings are missing all the `as*()` and `with*()` functions.
I use this as a temporary workaround:

    export class RequestBuilder {
        client: any;
        transformers: any;
        useJsonp: any;
        constructor(client: any);
	    /**
	    * Adds a user-defined request transformer to the RequestBuilder.
	    *
	    * @method addHelper
	    * @param {String} name The name of the helper to add.
	    * @param {Function} fn The helper function.
	    * @chainable
	    */
        static addHelper(name: any, fn: any): void;
	    /**
	    * Sends the request.
	    *
	    * @method send
	    * @return {Promise} A cancellable promise object.
	    */
        send(): any;
        /**
        * Missing functions
        **/
        asDelete: () => RequestBuilder;
        asGet: () => RequestBuilder;
        asHead: () => RequestBuilder;
        asOptions: () => RequestBuilder;
        asPatch: () => RequestBuilder;
        asPost: () => RequestBuilder;
        asPut: () => RequestBuilder;
        asJsonp: () => RequestBuilder;
        withUrl: (url: any) => RequestBuilder;
        withContent: (content: any) => RequestBuilder;
        withBaseUrl: (baseUrl: any) => RequestBuilder;
        withParams: (params: any) => RequestBuilder;
        withResponseType: (responseType: any) => RequestBuilder;
        withTimeout: (timeout: any) => RequestBuilder;
        withHeader: (key: any, value: any) => RequestBuilder;
        withCredentials: (value: any) => RequestBuilder;
        withReviver: (reviver: any) => RequestBuilder;
        withReplacer: (replacer: any) => RequestBuilder;
        withProgressCallback: (progressCallback: any) => RequestBuilder;
        withCallbackParameterName: (callbackParameterName: any) => RequestBuilder;
    }

**Comment by chrisdostert** [comment] 2015-08-28 00:57
Duplicate of: aurelia/http-client/issues/94

**Comment by jods4** [comment] 2015-09-07 13:59
While this gets fixed, `HttpResponseMessage` also lacks all its properties (`statusCode`, `requestMessage` & co.)

**Comment by LBednar** [comment] 2015-09-29 18:36
Hello, how it looks with solution of this problem?? I also ran into this issue today. I apply the solutions posted above temporary and it works.

**Comment by EisenbergEffect** [comment] 2015-10-23 14:43
Full api, types and docs added to source. Going out in next release.

**Closed by EisenbergEffect** 2015-10-23 14:43 UTC
